### ISSUE TITLE
drawfs.json out of date and could benefit from QA pass

### ISSUE THREAD

**Issue by AeroDeveloper** [ogdenwebb/drg-randomizer#1]
Hi, I wanted to know if it would be OK to contribute to this repository using a pull request from my fork. 

I noticed that the dwarfs.json file is out of date and may benefit from a QA pass as well to address syntax/type standardization.  My fork has a modified dwarfs.json, and builds successfully with the Nim compiler (compiled from source with tag v1.6.6) but am open to any other tests you would want to perform to validate my changes.

**Comment by ogdenwebb** [comment]
Hello, yeah, it's totally fine if you want to contribute to this project. 

In the past I've created this tool for a person to complete my specific request on Twitch related to Deep Rock Galactic. Because DRG doesn't have a mod like that to generate a random layout and I have literally zero knowledge about Unreal Engine scripting, I decided to go with Nim.

So yeah, that would be great. :)
